blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/your-username/shadcn-logos/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/your-username/shadcn-logos/security
    about: Report security vulnerabilities privately